# Generated by Django 6.0.2 on 2026-02-28 14:03

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('price_per_share', models.DecimalField(decimal_places=2, help_text='Цена за одну долю', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_shares', models.PositiveIntegerField(help_text='Сколько всего долей выпущено')),
                ('available_shares', models.PositiveIntegerField(help_text='Сколько долей осталось для покупки')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PRESALE', 'Сбор средств (Пресейл)'), ('ACTIVE', 'Сбор закрыт / Активен'), ('SOLD', 'Продан полностью (Экзит)')], db_index=True, default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shares_amount', models.PositiveIntegerField(default=0)),
                ('average_buy_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owners', to='catalog.project')),
            ],
            options={
                'verbose_name': 'Владение долей',
                'verbose_name_plural': 'Владения долями',
                'db_table': 'ownerships',
                'unique_together': {('user', 'project')},
            },
        ),
    ]
