# Generated by Django 6.0.2 on 2026-03-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_project_image_project_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Если включено, категория не будет выводиться в общем списке на фронтенде.', verbose_name='Скрыть из каталога'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Если включено, проект не будет виден в общем каталоге, но будет доступен по прямой ссылке (например, для токена BMK).', verbose_name='Скрыть из каталога'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_new',
            field=models.BooleanField(default=True, help_text='Показывать проект в специальном блоке новинок на фронтенде.', verbose_name='Новинка'),
        ),
    ]
