# Generated by Django 6.0.2 on 2026-03-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_is_hidden_project_is_hidden_project_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='category_es',
        ),
        migrations.RemoveField(
            model_name='project',
            name='category_ru',
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
