# Generated by Django 6.0.2 on 2026-03-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_project_category_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.TextField(blank=True, help_text='Выводится на карточках в карусели на главной странице', max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_en',
            field=models.TextField(blank=True, help_text='Выводится на карточках в карусели на главной странице', max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_es',
            field=models.TextField(blank=True, help_text='Выводится на карточках в карусели на главной странице', max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_ru',
            field=models.TextField(blank=True, help_text='Выводится на карточках в карусели на главной странице', max_length=500, null=True, verbose_name='Краткое описание'),
        ),
    ]
