# Generated by Django 6.0.2 on 2026-03-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_project_short_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
            ],
            options={
                'verbose_name': 'Токен',
                'verbose_name_plural': 'Токены',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.project',),
        ),
        migrations.CreateModel(
            name='TokenOwnership',
            fields=[
            ],
            options={
                'verbose_name': 'Владение токеном',
                'verbose_name_plural': 'Владения токенами',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.ownership',),
        ),
        migrations.AddField(
            model_name='project',
            name='is_token',
            field=models.BooleanField(default=False, help_text='Если включено, актив будет считаться токеном и управляться в отдельном разделе админки.', verbose_name='Это токен'),
        ),
    ]
