# Generated by Django 6.0.2 on 2026-03-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_token_tokenownership_project_is_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_es',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
