# Generated by Django 6.0.2 on 2026-04-14 15:51

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_project_image_en_project_image_es_project_image_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_es',
            field=tinymce.models.HTMLField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_ru',
            field=tinymce.models.HTMLField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, help_text='Выводится на карточках в карусели на главной странице', max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description_en',
            field=tinymce.models.HTMLField(blank=True, help_text='Выводится на карточках в карусели на главной странице', max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description_es',
            field=tinymce.models.HTMLField(blank=True, help_text='Выводится на карточках в карусели на главной странице', max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description_ru',
            field=tinymce.models.HTMLField(blank=True, help_text='Выводится на карточках в карусели на главной странице', max_length=500, null=True, verbose_name='Краткое описание'),
        ),
    ]
