# Generated by Django 6.0.2 on 2026-04-01 18:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена ($)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets_images/', verbose_name='Изображение')),
                ('is_unique', models.BooleanField(default=False, help_text="Если включено, актив продается в одни руки и после покупки получает статус 'Продано'.", verbose_name='Уникальный актив')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('ACTIVE', 'В продаже'), ('SOLD', 'Продано')], db_index=True, default='DRAFT', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Актив (Проект целиком)',
                'verbose_name_plural': 'Активы (Проекты целиком)',
                'db_table': 'assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoldUniqueAsset',
            fields=[
            ],
            options={
                'verbose_name': 'Проданный уникальный актив',
                'verbose_name_plural': 'Проданные уникальные активы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog_assets.asset',),
        ),
        migrations.CreateModel(
            name='AssetOwnership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена покупки')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owners', to='catalog_assets.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_ownerships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Владение активом',
                'verbose_name_plural': 'Владения активами',
                'db_table': 'asset_ownerships',
                'ordering': ['-purchased_at'],
            },
        ),
    ]
