# Generated by Django 6.0.2 on 2026-04-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='asset',
            name='description_es',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='asset',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='asset',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='assets_images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='asset',
            name='image_es',
            field=models.ImageField(blank=True, null=True, upload_to='assets_images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='asset',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to='assets_images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='asset',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='asset',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='asset',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
