# Generated by Django 6.0.2 on 2026-04-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_assets', '0002_asset_description_en_asset_description_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Если включено, проект не будет виден в общем каталоге, но будет доступен по прямой ссылке (например, для токена BMK).', verbose_name='Скрыть из каталога'),
        ),
        migrations.AddField(
            model_name='asset',
            name='is_new',
            field=models.BooleanField(default=True, help_text="Если включено, актив отображается с пометкой 'Новый' на витрине.", verbose_name='Новый актив'),
        ),
    ]
