# Generated by Django 6.0.2 on 2026-04-14 15:51

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_assets', '0003_asset_is_hidden_asset_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description_es',
            field=tinymce.models.HTMLField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description_ru',
            field=tinymce.models.HTMLField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('ACTIVE', 'В продаже'), ('SOLD', 'Продано')], default='DRAFT', max_length=20, verbose_name='Статус'),
        ),
    ]
