# Generated by Django 6.0.2 on 2026-06-10 12:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_assets', '0004_alter_asset_description_alter_asset_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название категории')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название категории')),
                ('name_es', models.CharField(max_length=255, null=True, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг (для URL)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets_categories/', verbose_name='Изображение')),
                ('is_hidden', models.BooleanField(default=False, help_text='Если включено, категория не будет выводиться в общем списке на витрине.', verbose_name='Скрыть из каталога')),
            ],
            options={
                'verbose_name': 'Категория актива',
                'verbose_name_plural': 'Категории активов',
                'db_table': 'asset_categories',
            },
        ),
        migrations.CreateModel(
            name='AssetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название тега')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Название тега')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Название тега')),
                ('name_es', models.CharField(max_length=50, null=True, verbose_name='Название тега')),
                ('slug', models.SlugField(blank=True, max_length=60, null=True, unique=True, verbose_name='Слаг (для фильтров)')),
                ('color', models.CharField(default='#3B82F6', help_text='Например: #3B82F6', max_length=7, verbose_name='Цвет плашки (HEX)')),
                ('show_on_card', models.BooleanField(default=True, help_text='Если выключено, тег отобразится только на детальной странице ассета.', verbose_name='Показывать на карточке')),
            ],
            options={
                'verbose_name': 'Тег актива',
                'verbose_name_plural': 'Теги активов',
                'db_table': 'asset_tags',
            },
        ),
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название характеристики')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Название характеристики')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Название характеристики')),
                ('name_es', models.CharField(max_length=100, null=True, verbose_name='Название характеристики')),
                ('icon', models.CharField(blank=True, help_text="Название иконки для фронтенда, например: 'Users', 'TrendingUp', 'Activity'.", max_length=50, verbose_name='Иконка (Lucide)')),
                ('show_on_card', models.BooleanField(default=True, help_text='Определяет, выводить ли эту характеристику на плитке в общем каталоге.', verbose_name='Показывать на карточке')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше строчка отобразится в таблице аудита.', verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Определение характеристики (DD)',
                'verbose_name_plural': 'Определения характеристик (DD)',
                'db_table': 'asset_metric_definitions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Если включено, проект не будет виден в общем каталоге, но будет доступен по прямой ссылке.', verbose_name='Скрыть из каталога'),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='catalog_assets.assetcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='assets', to='catalog_assets.assettag', verbose_name='Теги актива'),
        ),
        migrations.CreateModel(
            name='AssetMetricValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(help_text="Например: '$350/мес', '2 человека', 'Органика (95%)'.", max_length=255, verbose_name='Значение')),
                ('value_ru', models.CharField(help_text="Например: '$350/мес', '2 человека', 'Органика (95%)'.", max_length=255, null=True, verbose_name='Значение')),
                ('value_en', models.CharField(help_text="Например: '$350/мес', '2 человека', 'Органика (95%)'.", max_length=255, null=True, verbose_name='Значение')),
                ('value_es', models.CharField(help_text="Например: '$350/мес', '2 человека', 'Органика (95%)'.", max_length=255, null=True, verbose_name='Значение')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='catalog_assets.asset', verbose_name='Актив')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog_assets.metricdefinition', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Значение характеристики лота',
                'verbose_name_plural': 'Значения характеристик лота',
                'db_table': 'asset_metric_values',
                'unique_together': {('asset', 'metric')},
            },
        ),
    ]
