# Generated by Django 6.0.2 on 2026-06-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_assets', '0005_assetcategory_assettag_metricdefinition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='short_description',
            field=models.CharField(blank=True, help_text='Буквально 1-2 предложения для красивого отображения на плитке в каталоге.', max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='asset',
            name='short_description_en',
            field=models.CharField(blank=True, help_text='Буквально 1-2 предложения для красивого отображения на плитке в каталоге.', max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='asset',
            name='short_description_es',
            field=models.CharField(blank=True, help_text='Буквально 1-2 предложения для красивого отображения на плитке в каталоге.', max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='asset',
            name='short_description_ru',
            field=models.CharField(blank=True, help_text='Буквально 1-2 предложения для красивого отображения на плитке в каталоге.', max_length=500, null=True, verbose_name='Краткое описание'),
        ),
    ]
