# Generated by Django 6.0.2 on 2026-05-22 09:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Если отключено, виджет чата не будет отображаться на фронтенде.', verbose_name='Ассистент активен')),
                ('model_name', models.CharField(choices=[('gpt-4o', 'OpenAI GPT-4o'), ('gpt-4o-mini', 'OpenAI GPT-4o-Mini'), ('claude-3-5-sonnet', 'Anthropic Claude 3.5 Sonnet'), ('custom-proxy', 'Локальный / Кастомный Прокси')], default='gpt-4o-mini', max_length=50, verbose_name='Используемая LLM модель')),
                ('temperature', models.FloatField(default=0.3, help_text='Чем ниже значение (например, 0.1-0.3), тем более строгими, точными и финансово-обоснованными будут ответы ассистента.', verbose_name='Температура (Креативность)')),
                ('system_prompt', models.TextField(help_text='Здесь задаются Tone of Voice, ограничения, правила поведения и базовая информация о платформе BiMark.', verbose_name='Системный промт (Инструкции для ИИ)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
            ],
            options={
                'verbose_name': 'Конфигурация ИИ Ассистента',
                'verbose_name_plural': 'Конфигурация ИИ Ассистента',
            },
        ),
    ]
