# Generated by Django 6.0.2 on 2026-05-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantconfig',
            name='custom_proxy_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API Ключ кастомного прокси'),
        ),
        migrations.AddField(
            model_name='assistantconfig',
            name='custom_proxy_url',
            field=models.URLField(blank=True, help_text="Заполняется только при выборе 'Кастомный Прокси'.", null=True, verbose_name='Кастомный Base URL (для прокси)'),
        ),
        migrations.AddField(
            model_name='assistantconfig',
            name='deepseek_api_key',
            field=models.CharField(blank=True, help_text='Ключ от платформы api.deepseek.com', max_length=255, null=True, verbose_name='API Ключ DeepSeek'),
        ),
        migrations.AddField(
            model_name='assistantconfig',
            name='openai_api_key',
            field=models.CharField(blank=True, help_text='Оставьте пустым, если используете только DeepSeek.', max_length=255, null=True, verbose_name='API Ключ OpenAI'),
        ),
        migrations.AlterField(
            model_name='assistantconfig',
            name='model_name',
            field=models.CharField(choices=[('gpt-4o', 'OpenAI GPT-4o'), ('gpt-4o-mini', 'OpenAI GPT-4o-Mini'), ('deepseek-chat', 'DeepSeek Chat (V3)'), ('deepseek-reasoner', 'DeepSeek Reasoner (R1)'), ('custom-proxy', 'Кастомный OpenAI-совместимый Прокси')], default='gpt-4o-mini', max_length=50, verbose_name='Используемая модель'),
        ),
        migrations.AlterField(
            model_name='assistantconfig',
            name='system_prompt',
            field=models.TextField(help_text='Здесь задаются Tone of Voice, ограничения и базовая информация о BiMark.', verbose_name='Системный промт (Инструкции для ИИ)'),
        ),
        migrations.AlterField(
            model_name='assistantconfig',
            name='temperature',
            field=models.FloatField(default=0.3, help_text='Рекомендуется 0.1 - 0.4 для точных финансовых консультаций. Для deepseek-reasoner этот параметр игнорируется API.', verbose_name='Температура (Креативность)'),
        ),
        migrations.AlterField(
            model_name='assistantconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
