# Generated by Django 6.0.2 on 2026-05-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_assistantconfig_custom_proxy_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantQuickReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='/', help_text="Например: '/' для главной, '/token' для страницы токена.", max_length=255, verbose_name='Путь страницы (URL)')),
                ('locale', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('es', 'Spanish')], default='en', max_length=10, verbose_name='Язык интерфейса')),
                ('text', models.CharField(max_length=255, verbose_name='Текст быстрой подсказки')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем левее/выше будет кнопка на сайте.', verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Быстрая подсказка сайта',
                'verbose_name_plural': 'Быстрые подсказки сайта',
                'db_table': 'assistant_quick_replies',
                'ordering': ['order', 'id'],
            },
        ),
    ]
