# Generated by Django 6.0.2 on 2026-06-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_assistantquickreply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistantconfig',
            options={'verbose_name': 'Настройка ИИ-Агента', 'verbose_name_plural': 'Настройки ИИ-Агента'},
        ),
        migrations.AddField(
            model_name='assistantconfig',
            name='is_tg_bot_active',
            field=models.BooleanField(default=False, help_text='Если выключено, бот будет игнорировать сообщения пользователей.', verbose_name='Включить Telegram-бота'),
        ),
        migrations.AddField(
            model_name='assistantconfig',
            name='tg_bot_token',
            field=models.CharField(blank=True, help_text='Токен, полученный от @BotFather', max_length=255, null=True, verbose_name='Telegram Bot Token'),
        ),
    ]
