# Generated by Django 6.0.2 on 2026-02-28 14:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма всегда положительная. Тип транзакции определяет, плюс это или минус.', max_digits=12)),
                ('type', models.CharField(choices=[('DEPOSIT', 'Пополнение'), ('WITHDRAW', 'Вывод'), ('PURCHASE', 'Покупка актива'), ('REFERRAL', 'Реферальный бонус')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'В обработке'), ('COMPLETED', 'Успешно'), ('FAILED', 'Отклонено / Ошибка')], db_index=True, default='PENDING', max_length=20)),
                ('reference_id', models.CharField(blank=True, help_text='ID во внешней системе', max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Кошелек',
                'verbose_name_plural': 'Кошельки',
                'db_table': 'wallets',
            },
        ),
    ]
