# Generated by Django 6.0.2 on 2026-04-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_transaction_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('DEPOSIT', 'Пополнение'), ('WITHDRAW', 'Вывод'), ('PURCHASE', 'Покупка долей'), ('PURCHASE_ASSET', 'Покупка проекта целиком'), ('REFERRAL', 'Реферальный бонус')], db_index=True, max_length=20),
        ),
    ]
