# Generated by Django 6.0.2 on 2026-04-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_crypto_wallet', models.CharField(blank=True, default='', help_text='Этот кошелек будет отображаться пользователям на сайте', max_length=100, verbose_name='Кошелек компании (TRC20)')),
            ],
            options={
                'verbose_name': 'Настройки оплаты',
                'verbose_name_plural': 'Настройки оплаты',
            },
        ),
        migrations.CreateModel(
            name='AssetTransaction',
            fields=[
            ],
            options={
                'verbose_name': 'Покупка актива',
                'verbose_name_plural': 'Покупки активов',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billing.transaction',),
        ),
        migrations.CreateModel(
            name='ProjectTransaction',
            fields=[
            ],
            options={
                'verbose_name': 'Покупка проекта',
                'verbose_name_plural': 'Покупки проектов',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billing.transaction',),
        ),
    ]
