# Generated by Django 6.0.2 on 2026-03-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Тексты сайта (JSON)',
                'verbose_name_plural': 'Тексты сайта (JSON)',
                'managed': False,
            },
        ),
    ]
