# Generated by Django 6.0.2 on 2026-03-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_referral_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Индивидуальный реферальный процент. Если пусто, используется базовый.', max_digits=5, null=True),
        ),
    ]
